apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-home-deployment
spec:
  replicas: 1 # שני מופעים לשרידות
  selector:
    matchLabels:
      app: smart-home
  template:
    metadata:
      labels:
        app: smart-home
    spec:
      containers:
        - name: smart-home-api
          image: denniszo/smart-home-backend:1.0.0
          env:
            - name: HA_URL
              valueFrom:
                secretKeyRef:
                  name: ha-credentials
                  key: HA_URL
            - name: HA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ha-credentials
                  key: HA_TOKEN
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ha-credentials
                  key: TELEGRAM_TOKEN
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: ha-credentials
                  key: TELEGRAM_CHAT_ID
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ha-credentials
                  key: GEMINI_API_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ha-credentials
                  key: MONGO_URI
            - name: MONGO_DB_NAME
              value: "smarthome_db"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
