apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-home-deployment
spec:
  replicas: 1 # שני מופעים לשרידות
  selector:
    matchLabels:
      app: smart-home
  template:
    metadata:
      labels:
        app: smart-home
    spec:
      containers:
      - name: smart-home-api
        image: denniszo/smart-home-backend:latest
        ports:
        - containerPort: 80
        env:
        - name: HA_URL
          valueFrom:
            secretKeyRef:
              name: ha-credentials
              key: HA_URL
        - name: HA_TOKEN
          valueFrom:
            secretKeyRef:
              name: ha-credentials
              key: HA_TOKEN
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: ha-credentials
              key: TELEGRAM_TOKEN
        - name: TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: ha-credentials
              key: TELEGRAM_CHAT_ID      
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: smart-home-service
spec:
  selector:
    app: smart-home
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
  type: LoadBalancer # זה ייתן לך IP פנימי בבית לגשת אליו